spring:
  h2:
  console:
    enabled: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb

logging:
  level:
    org:
      hibernate:
        stat=debug: